package imgix

var sourceDescriptions = map[string]string{
	"id":                      "Id of the source",
	"type":                    "Type of the resource. This will be always sources.",
	"name":                    "Source display name. Does not impact how images are served.",
	"deployment_status":       "Current deployment status. Possible values are deploying, deployed, disabled, and deleted.",
	"enabled":                 "Whether or not a Source is enabled and capable of serving traffic.",
	"date_deployed":           "Unix timestamp of when this Source was deployed.",
	"secure_url_token":        "Signing token used for securing images. Only present if deployment.secure_url_enabled is true.",
	"wait_for_deployed":       "Determines if Terraform should wait for deployed status after any change.",
	"allows_upload":           "Whether imgix has the right permissions for this Source to upload to origin.",
	"annotation":              "Any comment on the specific deployment.",
	"cache_ttl_behavior":      "Policy to determine how the TTL on imgix images is set.",
	"cache_ttl_error":         "TTL (in seconds) for any error image served when unable to fetch a file from origin.",
	"cache_ttl_value":         "TTL (in seconds) for any error image served when unable to fetch a file from origin.",
	"crossdomain_xml_enabled": "Whether this Source should serve a Cross-Domain Policy file if requested.",
	"custom_domains":          "Non-imgix.net domains you want to use to access your images. Custom domains must be unique across all Sources and must be valid domains.",
	"default_params":          "Parameters that should be set on all requests to this Source.",
	"image_error":             "Image URL imgix should serve instead when a request results in an error.",
	"image_error_append_qs":   "Whether imgix should pass the parameters on the request that received an error to the URL described in image_error.",
	"image_missing":           "Image URL imgix should serve instead when a request results in a missing image.",
	"image_missing_append_qs": "Whether imgix should pass the parameters on the request that resulted in a missing image to the URL described in image_missing.",
	"imgix_subdomains":        "Subdomain you want to use on *.imgix.net to access your images.",
	"secure_url_enabled":      "Whether requests must be signed with the secure_url_token to be considered valid.",
	"deployment_type":         "Type of the deployment.",
	"s3_access_key":           "AWS Access Key ID.",
	"s3_secret_key":           "AWS S3 Secret Access Key.",
	"s3_bucket":               "AWS S3 bucket name.",
	"s3_prefix":               "The folder prefix prepended to the image path before resolving the image in S3.",
}
